// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/callback": {
    params: {};
  };
  "/formulas": {
    params: {};
  };
  "/formula/:formulaId": {
    params: {
      "formulaId": string;
    };
  };
  "/formula/new": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/callback" | "/formulas" | "/formula/:formulaId" | "/formula/new";
  };
  "Home.tsx": {
    id: "Home";
    page: "/";
  };
  "Callback.tsx": {
    id: "Callback";
    page: "/callback";
  };
  "MainPage.tsx": {
    id: "MainPage";
    page: "/" | "/formulas" | "/formula/:formulaId" | "/formula/new";
  };
  "Formulas.tsx": {
    id: "formulasIndex";
    page: "/";
  } | {
    id: "Formulas";
    page: "/formulas";
  };
  "Formula.tsx": {
    id: "Formula";
    page: "/formula/:formulaId";
  };
  "CreateFormula.tsx": {
    id: "CreateFormula";
    page: "/formula/new";
  };
};